export JAVA_HOME=$JAVA_HOME_CONDA_BACKUP
if [ uname -s == 'Darwin' ]; then
    export JAVA_DYLD_LIBRARY_PATH=$JAVA_DYLD_LIBRARY_PATH_BACKUP
else
    export JAVA_LD_LIBRARY_PATH=$JAVA_LD_LIBRARY_PATH_BACKUP
fi
